[tools]
apollo-rover = "latest"
"cargo:tree-sitter-cli" = "latest"
go = "latest"
"go:github.com/joshmedeski/sesh/v2" = "latest"
gum = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
"pipx:black" = "25.1.0"
rust = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
