# ─────────────────────────────────────────────────────────────────────────────
# Common Sesh Configuration
# ─────────────────────────────────────────────────────────────────────────────
# This file contains sessions and settings that work across ALL environments.
# These sessions are available on macOS, Ubuntu, and any other system.

# ─────────────────────────────────────────────────────────────────────────────
# Blacklist
# ─────────────────────────────────────────────────────────────────────────────
# Sessions to exclude from sesh list
blacklist = [
    "^scratch$",
    "^temp$",
    "^_",
]

# ─────────────────────────────────────────────────────────────────────────────
# Sort Order
# ─────────────────────────────────────────────────────────────────────────────
# Control the order sessions appear in the list
sort_order = ["config", "tmux", "zoxide"]

# ─────────────────────────────────────────────────────────────────────────────
# Default Session
# ─────────────────────────────────────────────────────────────────────────────
[default_session]
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"

# ─────────────────────────────────────────────────────────────────────────────
# Universal Sessions - Available on ALL machines
# ─────────────────────────────────────────────────────────────────────────────

[[session]]
name = "dotfiles 🔧"
path = "~/dotfiles"
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always ~/dotfiles"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "zsh config"
path = "~/.config/zsh"
startup_command = "nvim .zshrc"
preview_command = "bat --color=always ~/.zshrc"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim"
preview_command = "eza --tree --level=2 --icons --color=always ~/.config/nvim"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim ~/.config/sesh/sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "home (~)"
path = "~"
disable_startup_command = true
preview_command = "eza --all --icons --color=always ~"
